currentVersion=1.0.0-SNAPSHOT
projectGroup=sollecitom.backend-skeleton
org.gradle.jvmargs=-Xmx4g -XX:+UseZGC -XX:MaxMetaspaceSize=1g -XX:+HeapDumpOnOutOfMemoryError -Dkotlin.daemon.jvm.options=-XX:MaxMetaspaceSize=1g,-Xmx3g
org.gradle.parallel=true
org.gradle.workers.max=128
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.configuration-cache.problems=warn
org.gradle.daemon=false
dockerBaseImageRepository=eclipse-temurin
dockerBaseImageVariant=alpine
dockerBaseImageMajor=latest
dockerBaseImageParam=eclipse-temurin:26-alpine@sha256:e4f908886c1c50eaf59c18dab95ee75be7bf065808c931196eff9858adbe0a41
dockerRuntimeBaseImageVariant=jre-alpine
dockerRuntimeBaseImageParam=eclipse-temurin:26-jre-alpine@sha256:ff7c7f2b396864bebe42b0e29b41f4b8023d044179d021a14e9a711a1eb6a6e7
