currentVersion=1.0.0-SNAPSHOT
projectGroup=sollecitom.backend-skeleton
sollecitomGradlePluginsVersion=1.0.0
org.gradle.jvmargs=-Xmx4g -XX:+UseZGC -XX:MaxMetaspaceSize=1g -XX:+HeapDumpOnOutOfMemoryError -Dkotlin.daemon.jvm.options=-XX:MaxMetaspaceSize=1g,-Xmx3g
org.gradle.parallel=true
org.gradle.workers.max=128
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.configuration-cache.problems=warn
org.gradle.daemon=false
dockerBaseImageRepository=eclipse-temurin
dockerBaseImageVariant=alpine
dockerBaseImageMajor=latest
dockerBaseImageParam=eclipse-temurin:26-alpine@sha256:31c7e87c27d5dad4a4a1db0f90d269d1864b7838eb24ebc10417c2a8161caf13
dockerRuntimeBaseImageVariant=jre-alpine
dockerRuntimeBaseImageParam=eclipse-temurin:26-jre-alpine@sha256:1940b62cc310d703353bf1bb0ba064c9fd99357d746ef33e5493b4bb50d1a672
