currentVersion=1.0.0-SNAPSHOT
projectGroup=sollecitom.backend-skeleton
sollecitomGradlePluginsVersion=1.0.0
org.gradle.jvmargs=-Xmx4g -XX:+UseZGC -XX:MaxMetaspaceSize=1g -XX:+HeapDumpOnOutOfMemoryError -Dkotlin.daemon.jvm.options=-XX:MaxMetaspaceSize=1g,-Xmx3g
org.gradle.parallel=true
org.gradle.workers.max=128
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.configuration-cache.problems=warn
org.gradle.daemon=false
dockerBaseImageRepository=eclipse-temurin
dockerBaseImageVariant=alpine
dockerBaseImageMajor=latest
dockerBaseImageParam=eclipse-temurin:26-alpine@sha256:048e4cfc893da1d2f7424dd510bd2ebf34b91391916f25a57f6facf42d7a3add
dockerRuntimeBaseImageVariant=jre-alpine
dockerRuntimeBaseImageParam=eclipse-temurin:26-jre-alpine@sha256:76868ba39e145de9f157b5e58a4e2f8568d9cb066c66eca0c4372ec95bc486b3
